apiVersion: simon/v1alpha1
kind: Config
metadata:
  name: simon-paib-config
spec:
  cluster:
    customConfig: example/test-cluster
  customConfig:
    shufflePod: true
    workloadTuningConfig:
      ratio: 0.9
      seed: 233
    typicalPodsConfig:
      isInvolvedCpuPods: false
      podPopularityThreshold: 95
      isConsideredGpuResWeight: false