apiVersion: simon/v1alpha1
kind: Config
metadata:
  name: simon-paib-config
spec:
  cluster:
    customConfig: example/test-cluster
  customConfig:
    shufflePod: true
    typicalPodsConfig:
      isInvolvedCpuPods: false
      podPopularityThreshold: 95
      isConsideredGpuResWeight: false
    exportConfig:
      nodeSnapshotCSVFilePrefix: "tony/node-snapshot"
    
      

# 样例
# apiVersion: simon/v1alpha1
# kind: Simon
# metadata:
#   name: example-config
# spec:
#   cluster:
#     customConfig: example/test-cluster
#     kubeConfig: ""
#   appList:
#     - name: app1
#       path: /path/to/app1
#       chart: false
#   newNode: ""
#   customConfig:
#     shufflePod: true
#     exportConfig:
#       podSnapshotYamlFilePrefix: "/path/to/pod/snapshot/yaml"
#       nodeSnapshotCSVFilePrefix: "/path/to/node/snapshot/csv"
#     workloadInflationConfig:
#       ratio: 1.2
#       seed: 233
#     workloadTuningConfig:
#       ratio: 0.9
#       seed: 233
#     newWorkloadConfig: ""
#     descheduleConfig:
#       ratio: 0.5
#       policy: "example-policy"
#     typicalPodsConfig:
#       isInvolvedCpuPods: false
#       podPopularityThreshold: 95
#       podIncreaseStep: 1
#       gpuResWeight: 0.5
