apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: gpu-rs-03
  name: gpu-rs-03
  namespace: pai-gpu
  annotations:
    alibabacloud.com/gpu-milli: "1000"
    alibabacloud.com/gpu-count: "4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-deploy-03
  template:
    metadata:
      labels:
        app: gpu-deploy-03
    spec:
      containers:
      - image: tensorflow:latest
        name: main
        resources:
          limits:
            cpu: 16
            memory: 36864Mi
          requests:
            cpu: 16
            memory: 36864Mi
      hostNetwork: true
