apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: gpu-rs-06
  name: gpu-rs-06
  namespace: pai-gpu
  annotations:
    alibabacloud.com/gpu-milli: "1000"
    alibabacloud.com/gpu-count: "7"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-deploy-06
  template:
    metadata:
      labels:
        app: gpu-deploy-06
    spec:
      containers:
      - image: tensorflow:latest
        name: main
        resources:
          limits:
            cpu: 28
            memory: 64512Mi
          requests:
            cpu: 28
            memory: 64512Mi
      hostNetwork: true
