apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: gpu-rs-07
  name: gpu-rs-07
  namespace: pai-gpu
  annotations:
    alibabacloud.com/gpu-milli: "1000"
    alibabacloud.com/gpu-count: "8"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-deploy-07
  template:
    metadata:
      labels:
        app: gpu-deploy-07
    spec:
      containers:
      - image: tensorflow:latest
        name: main
        resources:
          limits:
            cpu: 32
            memory: 76800Mi
          requests:
            cpu: 32
            memory: 76800Mi
      hostNetwork: true
