apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: gpu-rs-00
  name: gpu-rs-00
  namespace: pai-gpu
  annotations:
    alibabacloud.com/gpu-milli: "1000"
    alibabacloud.com/gpu-count: "1"
spec:
  replicas: 10
  selector:
    matchLabels:
      app: gpu-deploy-00
  template:
    metadata:
      labels:
        app: gpu-deploy-00
    spec:
      containers:
      - image: tensorflow:latest
        name: main
        resources:
          limits:
            cpu: 4
            memory: 9216Mi
          requests:
            cpu: 4
            memory: 9216Mi
      hostNetwork: true
