apiVersion: v1
kind: Node
metadata:
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: pai-node-264
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ''
    alibabacloud.com/gpu-card-model: V100
    node-ip: 192.168.1.108
  name: pai-node-264
status:
  allocatable:
    alibabacloud.com/gpu-count: '8'
    alibabacloud.com/gpu-milli: '1000'
    cpu: 192
    memory: 1505762Mi
    pods: '110'
  capacity:
    alibabacloud.com/gpu-count: '8'
    alibabacloud.com/gpu-milli: '1000'
    cpu: 192
    memory: 1505762Mi
    pods: '110'
